server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestione_ticket
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        stat: debug
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
    com:
      ticketing: DEBUG
    org.springframework.security: INFO
    org.keycloak: INFO

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ticketing
  resource: ticketing-app
  public-client: true
  principal-attribute: preferred_username
  ssl-required: external
  use-resource-role-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  notification:
    email:
      enabled: false
  history:
    tracking:
      enabled: true
  default-page-size: 20
